<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'login',
                        'action'     =>  'logout',
                       )); ?>">Logout</a>

<br /><a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'profile',
                       )); ?>">Edit</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'achievements',
                       )); ?>">Achievements</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'certifications',
                       )); ?>">Certifications</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'contacts',
                       )); ?>">contacts</a>
   
<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'education',
                       )); ?>">education</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'experience',
                       )); ?>">experience</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'languages',
                       )); ?>">languages</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'publications',
                       )); ?>">Publications</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'refrences',
                       )); ?>">Refrences</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'seminars',
                       )); ?>">Seminars</a>

<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'index',
                        'action'     =>  'skills',
                       )); ?>">Skills</a>




<br /><img src="/images/<?php echo $this->userdata['profilePic'];?>"
 width="200" height="200" alt=<?php echo $this->userdata['profilePic'];?> />
<br />

<?php echo "First Name = ". $this->userdata['firstName']; ?><br />
<?php echo "Last Name = ". $this->userdata['lastName'];?><br />
<?php echo "Gender = ". $this->userdata['gender'];?><br />
<?php echo "Date Of Birth = ". $this->userdata['dateOfBirth'];?><br />
<?php echo "Website = ". $this->userdata['website'];?><br />
<?php echo "objective = ". $this->userdata['objective'];?><br />
<?php echo "region = ". $this->userdata['region'];?><br />
<?php echo "city = ". $this->userdata['city'];?><br />
<?php echo "street = ". $this->userdata['street'];?><br />
<?php echo "house = ". $this->userdata['house'];?><br />

<!-- achievementsdata -->
<br />
<?php echo "Achievements"; ?><br />
<?php foreach($this->achievementsdata as $t): ?>
   <!--<img src="/images/<?php echo $t['certificate']?>" width="200" height="200"/> -->
  <?php echo "title = ". $t['title']; ?><br />
  <?php echo "description = ".$t['description'];?><br /><br />
<?php endforeach; ?>

<!-- Certificationsdata -->
<?php echo "Certifications"; ?><br />
<?php foreach($this->Certificationsdata as $t): ?>
  <?php echo "title = ". $t['title']; ?><br />
  <?php echo "date Of Completion = ".$t['dateOfCompletion'];?><br />
  <?php echo "description = ".$t['description'];?><br /><br />
<?php endforeach; ?>

<!-- Contactsdata -->
<?php echo "Contacts"; ?><br />
<?php foreach($this->Contactsdata as $t): ?>
  <?php echo "title = ". $t['title']; ?><br />
  <?php echo "contact = ".$t['contact'];?><br /><br />
<?php endforeach; ?>


<!-- educationdata -->
<?php echo "education"; ?><br />
<?php foreach($this->educationdata as $t): ?>
  <?php echo "degree = ". $t['degree']; ?><br />
  <?php echo "regNo = ".$t['regNo'];?><br />
  <?php echo "fromDate = ". $t['fromDate']; ?><br />
  <?php echo "toDate = ". $t['toDate']; ?><br />
  <?php echo "description = ". $t['description']; ?><br /><br />
<?php endforeach; ?>
