
<h2><center><p>user index</p></center></h2>
<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'login',
                        'action'     =>  'logout',
                       )); ?>">Logout</a>




<?php
//....profile......
echo "profile";
echo $this->profileForm;

//....education.....
echo "education";
echo $this->eduForm;

//....Achievements.....
echo "Achievements";
echo $this->achForm;

//....Certifications.....
echo "Certifications";
echo $this->certForm;

//....Contacts.....
echo "Contacts";
echo $this->ContactsForm;

//....Experience.....
echo "Experience";
echo $this->ExperienceForm;

//....Publications.....
echo "Publications";
echo $this->PublicationsForm;

//....Refrences.....
echo "Refrences";
echo $this->RefrencesForm;

//....Seminars.....
echo "Seminars";
echo $this->SeminarsForm;

//....Skills.....
echo "Skills";
echo $this->SkillsForm;
?>


