
<h2><center><p>user index</p></center></h2>
<a id="Logout" href="<?php echo $this->Url(
                array(
                        'controller' =>  'login',
                        'action'     =>  'logout',
                       )); ?>">Logout</a>


<?php
//....profile......
echo "profile";
echo $this->profileForm;
?>


<?php
//....education.....
echo "education";
echo $this->eduForm;
?>

<?php
//....Achievements.....
echo "Achievements";
echo $this->achForm;
?>

<?php
//....Certifications.....
echo "Certifications";
echo $this->certForm;
?>

<?php
//....Contacts.....
echo "Contacts";
echo $this->ContactsForm;
?>

<?php
//....Experience.....
echo "Experience";
echo $this->ExperienceForm;
?>

<?php
//....Publications.....
echo "Publications";
echo $this->PublicationsForm;
?>

<?php
//....Refrences.....
echo "Refrences";
echo $this->RefrencesForm;
?>

<?php
//....Seminars.....
echo "Seminars";
echo $this->SeminarsForm;
?>

<?php
//....Skills.....
echo "Skills";
echo $this->SkillsForm;
?>

